### ISSUE TITLE
Setup Esllint

### ISSUE THREAD

**Issue by Vhndaree** [rabindratamang/hacker-news#1]
You can add eslint too. Since, this app is created with create-react-app. You do not need to add extra package here. You just need to create .eslintrc file and add setup and some custom rule. Basic `.eslintrc` file contains
```
{
  "env": {
    "es6": true,
    "node": true,
    "jasmine": true,
    "browser": true
  },
  "parser": "babel-eslint",
  "parserOptions": {
    "ecmaVersion": 2018,
    "sourceType": "module"
  },
  "extends": ["react-app"],
  "plugins": ["react"],
  "rules": {//Your custom rules goes here },
  "settings": {
    "react": {
      "pragma": "React", // Pragma to use, default to "React"
      "version": "detect" // React version. "detect" automatically picks the version you have installed.
    }
  }
}
```

There are several packages for more strict and most liked eslint configures. One is [eslint-config-leapfrog](https://yarnpkg.com/en/package/eslint-config-leapfrog)

And by combining eslint and prettier you can do auto formatting based on your preference. After configuring eslint you can add following command on your package.json under script like:
```
"scripts": {
    .............................
    "eslint": "eslint src",
    "eslint:fix": "eslint --fix src",
    "lint": "prettier && eslint",
    "lint:fix": "npm prettier:fix && npm eslint:fix",
    "prettier": "prettier '*/**/*.{js,jsx,scss,css}'",
    "prettier:fix": "prettier --write '*/**/*.{js,jsx,scss,css}'"
}
```

After setting all these hit `npm lint:fix` it automatically checks every file inside `src` directory and format your code s per your custom configuration.

**Comment by rabindratamang** [comment]
Thank you so much. I have added basic eslint config and script to this project. I will definitely enhance my configuration. Eslint and prettier works like a charm.
